
services:
  - type: web
    name: telegram-gemini-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python telegram_gemini_bot.py"
    envVars:
      - key: TELEGRAM_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: GEMINI_API_KEY
        value: YOUR_GEMINI_API_KEY
